module.exports.type = ["Red", "Rose", "White", "Sparkling"];

module.exports.variety = [
  "Albarino",
  "Amarone",
  "Arneis",
  "Asti Spumante",
  "Auslese",
  "Barbaresco",
  "Blanc de Blancs",
  "Beaujolais",
  "Blanc de Noirs",
  "Cabernet Franc",
  "Cabernet Sauvignon",
  "Carignan",
  "Charbono",
  "Chardonnay",
  "Chateaueuf-du-Pape",
  "Chianti Classico",
  "Fume Blanc",
  "Johannnisberg Riesling",
  "Lambrusco",
  "Liebfraumilch",
  "Malbec",
  "Meritage",
  "Mouvette",
  "Moscato",
  "Petit Verdot",
  "Petit Sirah",
  "Pinot Noir",
  "Sauvignon Blanc",
  "Valpolicella",
  "Viognier",
];
